import json
import logging
from typing import List
import os.path
from agent.base_agent import BaseAgent
from vo.idea_data import SeedIdeaResult, IdeaResult, load_SeedIdeaResult_from_dict
from vo.paper_data import Paper
from utils_tool import extract_json_between_markers
import time
import re
from utils_tool import init_logging, save_json_data_to_file, load_json_from_file

# Initialize logger
logger = logging.getLogger()

class SeedIdeaAgent(BaseAgent):

    def __init__(self, args):
        """
        Initialize the SeedIdeaAgent with necessary configurations and prompts.
        """
        BaseAgent.__init__(self, args)
        self.args = args
        self.system_msg = """"""
        self.task_name = "SeedIdeaAgent"

        # Load scientific discovery theory from file
        with open("prompts/a_general_theory_of_scientific discovery.txt", "r") as fr:
            scientific_discovery_theory = fr.readlines()
        self.scientific_discovery_theory = "".join(scientific_discovery_theory)

        # Example prompts for different types of ideas
        self.internal_idea_example = """```json\n[
            {
                "thinking": "Incorporating real-time data sources, such as ongoing research developments or recent publications, could keep the ResearchAgent’s outputs relevant and timely.",
                "idea": "Integrate real-time data feeds and recent publications into the ResearchAgent’s knowledge base to ensure that the generated ideas are aligned with the latest scientific advancements.",
                "keywords": "real-time Research data integration, recent publications Tracking, popular research publications tracking"
            },
            {
                "thinking": "The target paper highlights the challenge of transferring complex language abilities, such as humor generation, from LLMs to SLMs using a feedback-driven approach. While the study demonstrates that feedback from the LLM acting as both a teacher and a critic can significantly improve performance, it focuses solely on linguistic feedback. The referenced paper, 'MiniGPT-v2: large language model as a unified interface for vision-language multi-task learning,' introduces the concept of using a unified model to handle diverse vision-language tasks effectively. This suggests that incorporating multi-modal inputs (both visual and linguistic) can enhance model performance across various tasks.",
                "idea": "Investigate the effectiveness of multi-modal feedback mechanisms in enhancing the humor generation capabilities of Small Language Models (SLMs) by integrating visual and linguistic cues during the distillation process from Large Language Models (LLMs).",
                "keywords": "humor generation tasks, multi-modal feedback mechanisms, Small Language Models (SLMs), distillation, visual and linguistic cues"
            }
            ]\n```"""

        # self.scientific_idea_example = """```json\n[
        #     {
        #         "thinking": "By defining new scientific problems, we can explore the theoretical boundaries of MoE models. One potential area is the integration of reinforcement learning (RL) with MoE models to dynamically adjust expert selection based on task performance. This can lead to more efficient and adaptive models.",
        #         "idea": "Integrate reinforcement learning with MoE models to dynamically adjust expert selection based on task performance, enhancing efficiency and adaptability.",
        #         "keywords": "reinforcement learning, mixture of experts, dynamic expert selection, adaptive models",
        #         "rationale": "This idea addresses the challenge of static expert selection in MoE models, making them more adaptive and efficient. It is innovative as it combines RL with MoE, a relatively unexplored area, and has the potential to significantly improve model performance and efficiency.",
        #     },
        #     {
        #         "thinking": "The main limitation and deficiency of the current research of ResearchAgent is that it does not introduce the latest knowledge in the iterative process. Only relying on LLM's internal knowledge to iterate idea may lead to hallucinations and fail to use the latest knowledge. We can solve this problem by integrating an academic literature search engine and introducing more knowledge in the iterative process." ,
        #         "idea": "introduce the latest knowledge in the iteration process of ResearchAgent, improve the novelty and quality generated by idea and reduce hallucinations",
        #         "keywords": ["use LLM generate idea", "academic search engine", "reducing illusion"],
        #         "rationale": "This idea solves the problem that ResearchAgent can't introduce the latest literature to innovate in time, and puts forward an optimization method combining retrieval and iteration, which can effectively improve the effect of generating ideas by LLM, and is an idea worth exploring.
        #     }
        #     ]\n```"""

        with open("prompts/seed_idea_example_by_scientific_diescovery_theory.txt", "r") as f:
            self.scientific_idea_example = f.read().strip()
        # self.popular_idea_example = """```json\n[
        #     {
        #         "thinking": "The target paper relies heavily on existing literature, which may limit the generation of truly novel ideas. By integrating recent hot research directions synthetic data generation techniques, we can create high-quality synthetic research papers and datasets to augment the existing literature. This approach can help overcome the dependency on existing literature and introduce more diversity in the generated ideas.",
        #         "idea": "Integrate synthetic data generation techniques to create high-quality synthetic research papers and datasets, augmenting the existing literature and introducing more diversity in the generated ideas.",
        #         "keywords": "synthetic data generation, research idea generation, LLMs, data augmentation",
        #         "rationale": "This idea addresses the limitation of dependency on existing literature by introducing synthetic data, which can diversify the input data and potentially lead to more novel research ideas. The use of synthetic data generation is innovative and has the potential to enhance the robustness and creativity of the ResearchAgent, making it a strong candidate for top conference recognition.",
        #     }
        #     ]\n```"""
       # Load scientific discovery theory from file
        with open("prompts/seed_idea_example_by_hot_papers.txt", "r") as fr:
            popular_idea_example = fr.readlines()
        self.popular_idea_example = "".join(popular_idea_example)

        # JSON format for idea generation
        self.idea_json_format = """In <JSON>, provide the new idea list in JSON format, every idea with the following fields:
            - "thinking": The thought process behind proposing the new idea.
            - "idea": detail valuable and new ideas worth exploring.
            - "keywords": keywords that can help search in google scholar then you can find related paper.
            - "rationale": The reason for generating this idea. You can explain what challenge it solves, why this idea is innovative, and why it has the potential to develop into a proposal for a top conference..
            """
        self.scientific_idea_json_format = """In <JSON>, provide the new idea list in JSON format, every idea with the following fields:
            - "thinking": Explain the scientific ideas you want to propose to improve the current paper. Analyze the innovation of the idea, whether it conforms to common sense, and whether it is feasible. Specifically explain which theory is used to propose the new idea and explain the principle of the theory.
            - "idea": detail valuable and new ideas worth exploring. Each idea needs a title, followed by a detailed description of the content. The title and details are separated by a colon. Note that the topic should be reflected in the title (around 10 words).
            - "keywords": keywords that can help search in google scholar then you can find related paper.
            - "rationale": The reason for generating this idea. You can explain what challenge it solves, why this idea is innovative, and why it has the potential to develop into a proposal for a top conference..
            """

        self.scientific_idea_json_format2 = """
        - "thinking":Explain which scientific theory or method of discovery you used to come up with a new idea and why it can improve the current work. You should make sure that the new idea is reasonable and feasible. The thinking might be something like this: Based on the method 'Explore the limitations and shortcomings of the current method', we can first check the shortcomings and limitations of the input paper is....., then we can come up with a new idea......, because it can improve......, its innovation is...., it is feasible because...
        - "idea": detail valuable and new ideas worth exploring, should focus on the topic follow input target paper.
        - "keywords": keywords of the new idea, that can help search in google scholar then you can find related paper.
        - "rationale": The reason for generating this idea. You can explain what challenge it solves, why this idea is innovative, and why it has the potential to develop into a proposal for a top conference..
        """
        pass

    def run_llm_internal_method(self, paper:Paper, use_self_refine=False):
        """
        Generate ideas based on LLM's internal knowledge.
        """
        logger.info(f"SeedIdeaAgent paper:{paper.title} generate idea based on llm internal knowledge...")
        p1 = self._gen_prompt_for_mining_idea_based_on_llm_internal_knowledge(paper, use_self_refine)
        fail_times = 3
        try_times = 0
        seed_idea = SeedIdeaResult(seed_list=[], success=False)
        while try_times < fail_times:
            try:
                p1_result = self._call_llm(
                    sys="",
                    prompt=p1,
                    fail_times=1,
                    parse_data_flag=False
                )
                seed_idea = self._parse_idea_from_internal_knowledge(response=p1_result, prompt=p1)
                break
            except Exception as e:
                time.sleep(try_times)
                logger.info(f"SeedIdeaAgent | run_llm_internal_method failed try_times:{try_times}, e:{e}")
            try_times += 1
            logger.info(f"SeedIdeaAgent | run_llm_internal_method try_times:{try_times}")
        return seed_idea

    def run_popular_method(self, paper:Paper, qa_info:str, research_trending_info:str, topk_high_quality_paper_list:List, exist_idea:List, use_self_refine=False, use_few_shot_example=True):
        """
        Generate ideas based on popular knowledge.
        """
        logger.info(f"SeedIdeaAgent paper:{paper.title} start mining idea based on popular knowledge...")
        p2 = self._gen_prompt_for_mining_idea_based_on_popular_knowledge(
            paper,
            qa_info, # limitation可能已经提出来过了
            research_trending_info=research_trending_info,
            topk_high_quality_paper_list=topk_high_quality_paper_list,
            exist_idea=exist_idea,
            use_self_refine=use_self_refine,
            use_few_shot_example=use_few_shot_example
        )
        try_times = 0
        fail_times = 3
        popular_idea_list = []
        p2_result = ""
        while try_times < fail_times:
            try:
                p2_result = self._call_llm(
                    sys="",
                    prompt=p2,
                    fail_times=3,
                    parse_data_flag=False
                )
                popular_idea_list = self._parse_idea_from_popular_knowledge(
                    response=p2_result,
                    source="popular_knowledge"
                )
                break
            except Exception as e:
                time.sleep(try_times)
                logger.info(f"SeedIdeaAgent | run_popular_method failed try_times:{try_times}, e:{e}")
            try_times += 1
            logger.info(f"SeedIdeaAgent | run_popular_method try_times:{try_times}")
        return p2, p2_result, popular_idea_list


    def run_science_method(self, paper:Paper, exist_idea, use_self_refine=False, use_few_shot_example=True):
        """
        Generate ideas based on scientific discovery theories.
        """
        logger.info(f"SeedIdeaAgent paper:{paper.title} start mining idea based on science discovery idea...")
        p3 = self._gen_prompt_for_mining_idea_based_on_science_discovery_idea(
            paper, exist_idea, use_self_refine=use_self_refine, use_few_shot_example=use_few_shot_example
            )
        p3_result = None
        for try_cnt in range(3):
            try:
                p3_result = self._call_llm(
                    sys="",
                    prompt=p3,
                    fail_times=3,
                    parse_data_flag=False
                )
                science_discovery_idea_list = self._parse_idea_from_science_discovery_idea(p3_result)
                return p3, p3_result, science_discovery_idea_list
            except Exception as e:
                time.sleep(try_cnt)
                logger.info(f"SeedIdeaAgent | run_science_method | failed {try_cnt+1} times")
                print("prompt:", p3)
                print("llm_response:", p3_result)
                import pdb;pdb.set_trace()

        return p3, None, []

    def run(self, paper:Paper, research_trending_info:str, topk_high_quality_paper_list:List,
            use_llm_internal_knowledge=True,
            use_popular_trending=True,
            use_science_discovery_theory=True,
            use_self_refine = False
            ) -> [SeedIdeaResult, dict]:
        """
        Run the SeedIdeaAgent to generate seed ideas using different methods.
        """
        debug_info = {
            "title":paper.title,
            "research_trending_info":research_trending_info,
        }
        logger.info(f"SeedIdeaAgent paper:{paper.title} start...")
        exist_idea = []
        # 1. Generate ideas based on LLM's internal knowledge
        seed_idea = self.run_llm_internal_method(paper, use_self_refine)
        if use_llm_internal_knowledge:
            debug_info["inter_seed_idea"] = seed_idea.to_dict()
            exist_idea.extend([_.idea for _ in seed_idea.get_seed_list()])
        logger.info(f"SeedIdeaAgent | run_llm_internal_method | exist_idea size:{len(exist_idea)}")
        # 2. Generate ideas based on popular knowledge
        if use_popular_trending:
            p2, p2_result, popular_idea_list = self.run_popular_method(
                paper=paper,
                qa_info=seed_idea.paper_qa_info,
                research_trending_info=research_trending_info,
                topk_high_quality_paper_list=topk_high_quality_paper_list,
                exist_idea=exist_idea,
                use_self_refine=use_self_refine
            )
            debug_info["popular_seed_idea"] = {
                "prompt": p2,
                "llm_result": p2_result,
                "seed_list": [_.to_dict() for _ in popular_idea_list],
                "source":"popular"
            }
            exist_idea.extend([_.idea for _ in popular_idea_list])
            seed_idea.seed_list.extend(popular_idea_list)
            logger.info(f"SeedIdeaAgent | run_popular_method | exist_idea size:{len(exist_idea)}")
        # 3. Generate ideas based on scientific discovery theories
        if use_science_discovery_theory:
            p3, p3_result, science_discovery_idea_list = self.run_science_method(
                paper=paper,
                exist_idea=exist_idea,
                use_self_refine=use_self_refine
            )
            debug_info["science_seed_idea"] = {
                "prompt": p3,
                "llm_result": p3_result,
                "seed_list": [_.to_dict() for _ in science_discovery_idea_list],
                "source": "science_discovery"
            }
            seed_idea.seed_list.extend(science_discovery_idea_list)
        # TODO: Explore more methods for generating initial ideas
        return seed_idea, debug_info

    def gen_seed_idea_if_not_exist(
            self, paper:Paper,
            research_trending_info:str,
            topk_high_quality_paper_list:List,
            seed_idea_debug_info_file:str,
            seed_idea_file:str,
            use_llm_internal_knowledge=True,
            use_popular_trending=True,
            use_science_discovery_theory=True,
            use_self_refine=False,

    ) -> List:
        """
        Generate seed ideas if they do not already exist in the specified file.
        """
        st = time.time()
        logger.info(f"BFSIdeaExpandEngine | run | paper:{paper.title} start!")
        # TODO:seed除了当前的知识，后续也可以补充一些当前知识以外的知识
        # seed_idea_file = os.path.join(output_dir, "seed_idea_list.json")
        if not os.path.exists(seed_idea_file):
            # 1. Generate seed ideas using three different methods
            seed_idea_result, seed_idea_debug_info = self.run(
                paper, research_trending_info, topk_high_quality_paper_list,
                use_llm_internal_knowledge,
                use_popular_trending,
                use_science_discovery_theory,
                use_self_refine
            )
            save_json_data_to_file(seed_idea_result.to_dict(), seed_idea_file)
            save_json_data_to_file(seed_idea_debug_info, seed_idea_debug_info_file)
            logger.info(f"SeedIdeaAgent | gen_seed_idea_if_not_exist | save seed_idea_list to file:{seed_idea_file}, "
                        f"debug_info save to:{seed_idea_debug_info_file}")

        else:
            seed_idea_dict = load_json_from_file(seed_idea_file)
            seed_idea_result = load_SeedIdeaResult_from_dict(seed_idea_dict)
            logger.info(f"SeedIdeaAgent | gen_seed_idea_if_not_exist | load idea from file:{seed_idea_file}")
        seed_idea_list = seed_idea_result.get_seed_list()
        logger.info(f"BFSIdeaExpandEngine | run | gen {paper.title} seed idea done! we have "
                    f"{len(seed_idea_list)} seed idea! cost:{time.time() - st}")
        return seed_idea_list

    def _parse_idea_from_science_discovery_idea(self, response):
        """Parse ideas from the response based on scientific discovery theories."""
        return self._parse_idea_from_popular_knowledge(response, source="science_discovery")

    def _gen_prompt_for_mining_idea_based_on_science_discovery_idea(self,
                                                                    paper:Paper,
                                                                    exist_idea,
                                                                    use_self_refine=False,
                                                                    use_few_shot_example=True
                                                                    ):
        """Generate prompt for mining ideas based on scientific discovery theories."""
        prompt = f"""
            # Role
            You are an expert researcher in AI. You are family with Science Discovery Theory, and you can use these theory to propose some innovative and valuable research idea based on the information provided by users.
            # Skill: Follow the steps below to generate new ideas and idea for exploration
            1. Understanding the research topic of the target paper, Understand current research progress by analyzing related papers:
                - The target paper is the primary research study you aim to enhance or build upon through future research, serving as the central source and focus for identifying and developing the specific research idea.
                - The related papers are studies that are related to the primary research topic you are focusing on, and provide additional context and ideas that are essential for understanding and extending the target paper.
            2. Understanding of the science discovery theories:
                - Understand the meaning and methods of these theories, which provide rich guidance and methods to help you put forward new idea.
                - Think carefully about how these theories are applied to current research. For example, based on the theory of "Exploring the Limits and shortcomings of Current Methods", you first need to analyze the limitations and Shortcomings of the given target paper and related papers, and propose new research idea based on this.
            3. Use these theories to analyze the current target paper and related papers and put forward the new idea:
                - Select the most appropriate theories and methods that are most suitable for target paper, Please analyze the input paper and related work in detail by using these thoery of scientific discovery, and put forward a new idea based on the analysis results.
                - You need to know how to effectively use innovative theories to mine ideas. For example, based on the theory of "Exploring the Limits and shortcomings of Current Methods", you need to analyze the limitations and Shortcomings of the given target paper and related papers, and propose new research idea based on this.
                - You need to select appropriate theories and use these theories to propose new idea that improve the current paper.
                - You need to come up with creative, influential and feasible ideas.
            # Science Discovery Theories:
            1. Here are 10 general science discovery theories:. You can choose one or more of these to propose new scientific research ideas for the target paper.
            {self.scientific_discovery_theory}
            # Output Format
            {self.scientific_idea_json_format}"""
        if use_few_shot_example:
            prompt += f"""
            # Example
            and here are some example for the json format result, you can follow the format only, and need to proposal new idea according to the input bellow.
            {self.scientific_idea_example}\n\n
            """
        if use_self_refine:
            prompt += f"# Self-refine\n\nIn the thinking step, you can first think of about 10 new ideas and analyze the advantages and " \
                      f"disadvantages of each of them. Your final idea can absorb their advantages and discard their " \
                      f"disadvantages.\n"
        prompt += f"""# Input
            related papers titles:{paper.related_paper_titles}
            related papers abstracts:{paper.related_paper_abstract}
            target paper title:{paper.title}
            target paper abstract:{paper.abstract}
            here are the exist idea you should avoid:
            exist_idea:{exist_idea}
            # Requirements
            1. Output about 5 new idea worth exploring, make sure the new idea should be related to target paper, follow the target paper's topic for further improvement.
            2. You should aim for new research ideas that can potentially win best paper awards at top conferences like ACL and NeurIPS and ICLR and CVPR.
            3. Skip the theory of scientific discovery may not fit well with the target paper, the theory and method you used should make sense and be reasonable for the target paper.
            4. Thinking is your thought process. Please explain which theory you used in your thinking process.
            5. exist_idea is some ideas that have been proposed before, you need to propose some different one.
            6. It is necessary to ensure that the generated research idea is feasible based on the current scientific progress.
            7. Please output your thought process
            8. please thinking step by step
            # Output
            ## Thinking
            <output your thinking process here, explain why you choose these theory to discover new idea and why it should have change to win the best paper awards at top conferences
            ### 10 possible new ideas(weakness and strenth analysis)
            <MarkDownFormatFor10PossibleResult>
            ### Final 5 Most Innovative and Important Ideas
            <JSON>"""
        return prompt


    def _parse_idea_from_popular_knowledge(self, response, source):
        """
        Parse ideas from the response based on popular knowledge.
        """
        idea_dict_list = extract_json_between_markers(response)
        idea_result_list = []
        for idea_dict in idea_dict_list:
            idea = IdeaResult.init_from_dict(idea_dict)
            idea.source = source
            idea_result_list.append(idea)
        return idea_result_list

    def _gen_prompt_for_mining_idea_based_on_popular_knowledge(
            self, paper:Paper,
            target_paper_base_info,
            research_trending_info,
            exist_idea,
            topk_high_quality_paper_list=None,
            use_self_refine=False,
            use_few_shot_example=True):
        """Generate prompt for mining ideas based on popular knowledge."""
        prompt = f"""
            # Role
            You are an expert researcher in AI. Your goal is to propose some innovative and valuable research idea based on the target paper and the some high quality research trending.
            # Skills: Propose some innovative and valuable research idea follow the following steps:
            1. Understand the target paper and target_paper_base_info well.
            2. Understand the research_trending_info and high_quality_paper_list well, Analyze the latest innovations, ideas and methods they have used.
            3. List some technologies used in research_trending_info and high_quality_paper_list, analyze the feasibility of combining these technologies with target_paper_base_info, and analyze the advantages and disadvantages of the combination
            4. Come up with some innovative and valuable research idea
            # Input Data Description
            It is important to understand target_paper_base_info and research_trending_info:
            - target_paper_base_info provides some basic information and limitation information of the target paper.
            - research_trending_info and high_quality_paper_list: This data analyzes the current popular research trends and high-quality papers. You can get inspiration from them and draw on their latest methods, ideas, and innovations to come up with new ideas, but you must be different from them and make sure that the ideas you propose are reasonable.
            - exist_idea is some ideas that have been proposed before, you need to propose some different one.
            # OutputFormat
            {self.idea_json_format}\n\n"""
        if use_few_shot_example:
            prompt += f"""
            # Idea Example
            You can follow these examples to get a sense of how the idea should be formatted (but don't borrow the ideas themselves):
            {self.internal_idea_example}\n\n
            """
        prompt += f"""Input:
            target paper title:{paper.title}
            target paper abstract:{paper.abstract}
            target_paper_base_info:{target_paper_base_info}
            research_trending_info:{research_trending_info}
            high_quality_paper_list:{str(topk_high_quality_paper_list)}
            here are the exist idea you should avoid:
            exist_idea:{exist_idea}
            target_paper_base_info:{target_paper_base_info}\n\n
            """
        if use_self_refine:
            prompt += f"# Self-refine\n\n"
            prompt += f"In the thinking step, you can first think of about 10 new ideas and analyze the advantages and " \
                      f"disadvantages of each of them. Your final 5 idea can absorb their advantages and discard their " \
                      f"disadvantages."
        prompt += """
        # Requirements
            1. Output about 5 new idea worth exploring
            2. You should aim for new research ideas that can potentially win best paper awards at top conferences like ACL and NeurIPS and ICLR and CVPR.
            3. the research trending may not well match the target paper, the idea you made should be make sense and reasonable. Explain which trending or high quality paper your inspiration comes from. What is the original idea, what are the benefits of adopting this idea, and explain why it is feasible.
            4. exist_idea is some ideas that have been proposed before, you need to propose some different one
            5. please thinking step by step
        # Output:
        ## Thinking:
        <output your thinking process here, explained what new knowledge you used for new idea and why it make sense and why it should have change to win the best paper awards at top conferences>
        ### 10 possible new ideas(weakness and strenth analysis)
        <MarkDownFormatFor10PossibleResult>
        ## Final 5 Most Innovative and Important Ideas:
        <JSON>"""
        return prompt

    def _parse_idea_from_internal_knowledge(self, response:str, prompt:str) -> SeedIdeaResult:
        """Parse ideas from the response based on LLM's internal knowledge."""
        data = extract_json_between_markers(response)
        paper_qa = data.get('None',)
        if isinstance(paper_qa, dict):
            paper_qa = json.dumps(paper_qa, ensure_ascii=False)
        idea_dict_list = data.get('idea_list',[])
        assert len(idea_dict_list) > 0, "empty seed idea from internal knowledge"
        idea_result_list = []
        for idea_dict in idea_dict_list:
            idea = IdeaResult.init_from_dict(idea_dict)
            idea.source = "llm_inter_knowledge"
            idea_result_list.append(idea)
        # return paper_qa, idea_result_list
        return SeedIdeaResult(
            idea_result_list,
            paper_qa,
            prompt=prompt,
            llm_result=response,
            success=True
        )

    def _gen_prompt_for_mining_idea_based_on_llm_internal_knowledge(self, paper, use_self_refine=False, k=5, use_few_shot_example=True):
        """Generate prompt for mining ideas based on LLM's internal knowledge."""
        qa_info_with_idea_json_format = """
            should has qa and idea_list as the key.
            qa: fill the basic QA info here.
            idea_list: fill the new idea list, every idea should follow the idea formatted.
            ```json
            {
                "qa": ""
                "idea_list": []
            }
            ```
            """

        prompt = f"""
            # Role
            You are an expert researcher in AI. Your goal is to propose some innovative and valuable research idea based on target paper.
            # Skill: Generate subsequent exploration idea according to the following steps
            Understanding of the target paper, related papers is essential:
            - The target paper is the primary research study you aim to enhance or build upon through future research, serving as the central source and focus for identifying and developing the specific research idea.
            - Related papers are articles that are connected to the target paper. They provide a deeper understanding of the field of the target paper, help you expand the additional background of the target paper, and assist you in coming up with better ideas.
            step1: QA: Combine target_paper and referenced paper to answer the following information.
            1. What are the research topics addressed in this paper? What methods are used in existing work, and what are the main innovations of the current study?
            2. What are the weakness, limitations of the current paper and What aspects could be further investigated in future studies?
            step2: Propose some valuable and new research idea.
            """
        if use_few_shot_example:
            prompt += f"""
            # Idea Example
            You can follow these examples to get a sense of how the idea should be formatted (but don't borrow the ideas themselves):
            {self.internal_idea_example}
            """

        prompt += f"""
            # Output Format
            {qa_info_with_idea_json_format}
            # Idea Format
            {self.idea_json_format}
            # Input:
            target_title:{paper.title}
            target_abstract:{paper.abstract}
            related_paper_title:{paper.related_paper_titles}
            related_paper_abstract:{paper.related_paper_abstract}
            target_title:{paper.title}
            target_abstract:{paper.abstract}"""
        if use_self_refine:
            prompt += f"In the thinking step, you can first think of about 10 new ideas and analyze the advantages and " \
                      f"disadvantages of each of them. Your final idea can absorb their advantages and discard their " \
                      f"disadvantages."
        prompt += """
            # Requirements
            1. Output about final 5 new idea worth exploring
            2. You should aim for new research ideas that can potentially win best paper awards at top conferences like ACL and NeurIPS and ICLR and CVPR.\
            3. Please output your thought process
            4. please thinking step by step
            # Output:
            Thinking:
            <output your thinking process here, explain why it should have change to win the best paper awards at top conferences>
            New research idea that improve target_paper:
            <JSON>
            """
        return prompt